### ISSUE TITLE
idea: trigger checks with ci-like filters

### ISSUE THREAD

**Issue by batuhan** [batuhan/checkly-cli#4]
Checks should have a trigger option. 

## Direct trigger
```bash
checkly-cli run landing-page-test # for checks that have a `key`
checkly-cli run api "Check Name" # for api checks that don't have a `key`
checkly-cli run browser "Check Name" # for api checks that don't have a `key`
checkly-cli run --tags multiple,tags # run multiple checks by tag (in which order?)
``` 

_*Possible problem* If there are multiple checks with the same name, which one to run?_

## Trigger in CI/CD
After a deployment by a CD mechanism, we can also run a command like:

```bash
checkly-cli trigger # without any name or key
``` 

That would trigger, based on a configuration set on :

```yaml
checks:
  - name: test
    trigger_on:
      branch:
       - master
```

Another approach would be to set the triggers seperately. This would allow ordered runs perhaps?

```yaml
triggers:
  - name: test
    checks: # Basically a search query
      - tags_in: test
  - name: test-2
    checks: # Basically a search query
      - name: "test"
        checkType: "api"
    trigger_on:
      branch:
       - master
```
